top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_c')

def configure(conf):
    conf.load('compiler_c')

def build(bld):
    bld(features='c cprogram',
        source = 'test_gsl_interp.c',
        target = 'test_gsl_interp',
        includes = '/opt/local/include',
        lib = 'gsl',
        libpath = '/opt/local/lib',
        )

# vim:ft=python
