
def configure(conf):
    print "in src/configure"
    conf.env.CFLAGS = "-Wall -O3".split()
    # conf.env.CFLAGS = "-Wall -g -dH".split()
    # conf.env.LDFLAGS = "-dH"
    conf.env.INCLUDES = "../src /opt/local/include".split()
    conf.env.LIB      = "gsl gslcblas".split()
    conf.env.LIBPATH = '/Users/ksmith/lib'
    conf.env.CYTHONFLAGS = "-I../src"

def build(bld):

    bld(
        features = 'c cshlib',
        source = 'gsl_interp2d.c',
        target = 'gsl_interp2d'
        )

    bld(
        features = 'c cshlib pyext',
        source   = 'wrap_gsl_interp2d.pyx',
        target   = 'wrap_gsl_interp2d',
        use      = "NUMPY gsl_interp2d",
        )

    bld(
        features = 'c cshlib pyext',
        source   = '_field_trace.pyx',
        target   = '_field_trace',
        use      = "NUMPY",
        )

    bld(
        features = 'c cshlib pyext',
        source   = '_triangulate.pyx',
        target   = '_triangulate',
        use      = "NUMPY",
        )

    bld(
        features = 'c cshlib pyext',
        source = 'trace_integrator.c wrap_trace_integrator.pyx',
        target = 'wrap_trace_integrator',
        use = "NUMPY gsl_interp2d",
        )

# vim:ft=python
